import Head from "next/head";
import Feature from "~/components/home/Feature";
import Hero from "~/components/home/Hero";

import Nav from "~/components/home/Nav";
import Started from "~/components/home/Started";

export default function Home() {
  return (
    <>
      <Head>
        <title>todo-daily</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        {/* 开启响应式的布局？(没看到效果) */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      {/* 
        这里的最顶级使用main标签也可以，对搜索引擎的支持会好一些；m-auto使container整体居中；h-screen是撑满浏览器高度；w-full是撑满父元素宽度
        overflow-x-hidden是隐藏水平方向滚动条
      */}
      <div className="m-auto h-full w-full overflow-hidden sm:container">
        <Nav />
        <Hero />
        <Feature />
        <Started />
      </div>
    </>
  );
}
